### PR TITLE
Add option :allow_trailing_comma to JSON#parse

### PR DESCRIPTION
**Pull request by jspanjers**
I think it would be really nice to support JSON arrays with trailing  comma's!

### CODE REVIEW

**Comment by marcandre** [comment]
Nice PR 🎉

I don't know if this will be accepted (since this goes beyond the stated goal of sticking to the RFC).

If not, you should consider making a [json5](https://json5.org/) parser. The [one I know about](https://github.com/bartoszkopinski/json5) has 500k downloads despite saying "Experimental JSON5 Ruby parser - DO NOT USE". The specs are already written too :-)

**Comment by marcandre** [comment]
Note: we already deviate from the RFC, for example with NaN, so I think this PR should be accepted.

**Comment by marcandre** [comment]
@hsbt: can we allow this feature?

**Comment by jspanjers** [comment]
Hi there,

I've rebased my feature branch to the current master to resolve some merge conflicts.
I have also added the implementation for JRuby.

Please review this pull request again and/or approve running the workflow to run the tests.

**Comment by byroot** [comment]
I think we should do this. As pointed out, we already have an option to support `NaN` and `Infinity`, and we even support comments with no option to turn it off.

Trailing commas would be the only thing missing to be compatible with what's often referred to as "jsonc" (some `jsonc` specs also allow unquoted keys, but that's going a bit far).

I'll try to rebase this PR.

**Pull request closed without merging**
